# Generated by Django 2.2.3 on 2019-07-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='专辑名称')),
            ],
            options={
                'verbose_name': '专辑表',
                'verbose_name_plural': '专辑表',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='歌手名称')),
            ],
            options={
                'verbose_name': '歌手表',
                'verbose_name_plural': '歌手表',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='歌曲名称')),
                ('url', models.CharField(blank=True, max_length=30, null=True, verbose_name='歌曲链接')),
                ('time', models.CharField(blank=True, max_length=30, null=True, verbose_name='时长')),
                ('comment', models.IntegerField(blank=True, null=True, verbose_name='评论数')),
                (
                    'album',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netease.Album')),
                ('singer',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netease.Singer')),
            ],
            options={
                'verbose_name': '歌曲表',
                'verbose_name_plural': '歌曲表',
                'ordering': ('-id',),
            },
        ),
    ]
